### python -m venv venv
### venv\Scripts\activate  


## Numpy Basics

In [1]:
import numpy as np 

## Creating array From list

In [2]:
arr_1d = np.array([1,2,3])
print("1d array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array: ", arr_2d)

1d array:  [1 2 3]
2d array:  [[1 2 3]
 [4 5 6]]


## Numpy vs List

In [3]:
py_list = [1,2,3]
print("python list mul : ", py_list * 2)

np_array = np.array([[1,2,3], [4,5,6]])
print("numpy array mul : ", np_array * 2)

import time
start = time.time()

py_list = [i*2 for i in range(1000000)]
print("\n operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(100000000) * 2
print("\n operation time: ", time.time() - start)

python list mul :  [1, 2, 3, 1, 2, 3]
numpy array mul :  [[ 2  4  6]
 [ 8 10 12]]

 operation time:  0.09008002281188965

 operation time:  1.027040719985962


### Creating Numpy Array From Scratch

In [4]:
zeros = np.zeros((5,5))
print(zeros)

ones = np.ones((5,5))
print("\n",ones)

full = np.full((5,5), 69)
print("\n",full)

random = np.random.random((3,3))
print("\n",random)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[69 69 69 69 69]
 [69 69 69 69 69]
 [69 69 69 69 69]
 [69 69 69 69 69]
 [69 69 69 69 69]]

 [[0.75500755 0.9584364  0.27362787]
 [0.08703364 0.94682866 0.77007718]
 [0.36126359 0.06432876 0.95957764]]


## vector, matrices & tensor

In [5]:
vector = np.array([1,2,3])
print("\n", vector)

matrices = np.array([[1,2,3],
                     [4,5,6]])
print("\n",matrices)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("\n",tensor)


 [1 2 3]

 [[1 2 3]
 [4 5 6]]

 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [6]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("Shape: ", arr.shape)
print("dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Dtype: ", arr.dtype)

Shape:  (3, 3)
dimension:  2
Size:  9
Dtype:  int64


## Array Reshaping

In [7]:
arr = np.arange(12)
print("\n Original array: ", arr)

reshape = arr.reshape(3,4)
print("\n Reshaped array: ", reshape)

flattened = reshape.flatten()
print("\n Flatten array: ", flattened)

raveled = reshape.ravel()
print("\n Raveled array: ", raveled)

transpose = reshape.T
print("\n Transpose array: ", transpose)


 Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flatten array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
