# Numpy Array operation

In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Array Element: ", arr_2d[1,0])
print("Array Row: ", arr_2d[1])
print("Array Column: ", arr_2d[:,1])
print("Array : ", arr_2d[:,:])
print("Array : ", arr_2d.diagonal())

Array Element:  4
Array Row:  [4 5 6]
Array Column:  [2 5 8]
Array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array :  [1 5 9]


# Sorting

In [3]:
arr = np.array([8,5,2,5,3,7,0,1,3,6])
print("Sorted array :", np.sort(arr))

arr_1 = np.array([[9,8,7],
                  [6,5,4],
                  [3,2,1]])

print("Sorted 2D array :\n", np.sort(arr_1, axis=0))
print("Sorted 2D array :\n", np.sort(arr_1, axis=1))

Sorted array : [0 1 2 3 3 5 5 6 7 8]
Sorted 2D array :
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Sorted 2D array :
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


## Filters

In [4]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_no = number[number % 2 == 0]
print("Even No: ", even_no)
odd_no = number[number % 2 != 0]
print("Odd No: ", odd_no)

Even No:  [ 2  4  6  8 10]
Odd No:  [1 3 5 7 9]


## Filter with Mask

In [5]:
mask = number > 5
print("no greater than 5: ", number[mask])

no greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where

In [6]:
indecies = [0,2,4]
print(number[indecies])

where_rs = np.where(number > 5)
print("where clause: ", where_rs)
print("where clause array: ", number[where_rs])

condition_ar = np.where(number > 5, number*10000000000, number)
print(condition_ar)

[1 3 5]
where clause:  (array([5, 6, 7, 8, 9]),)
where clause array:  [ 6  7  8  9 10]
[           1            2            3            4            5
  60000000000  70000000000  80000000000  90000000000 100000000000]


## Adding And Removing Data

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combine = np.concatenate((arr1,arr2))
print(combine)

original = np.array([[1,2],[3,4]])
new_ar = np.array([[5,6]])

new_row = np.vstack((original, new_ar))

print("Original array :\n",original)
print("New array :\n",new_row)

col = np.array([[7], [8]])
new_col = np.hstack((original, col))
print("New array Column :\n",new_col)

[1 2 3 4 5 6]
Original array :
 [[1 2]
 [3 4]]
New array :
 [[1 2]
 [3 4]
 [5 6]]
New array Column :
 [[1 2 7]
 [3 4 8]]
